# Generated by Django 3.2.22 on 2023-11-02 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_country'),
        ('accounts', '0002_auto_20231027_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='home_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.country'),
        ),
    ]
