# Generated by Django 3.2.22 on 2023-10-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='capital',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='currency_code',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='country',
            name='currency_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='fips',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso3',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso_numeric',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='country',
            name='languages',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='postal_code_format',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='postal_code_regex',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='tld',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
